notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.net#fixmystreet"
    use_notice: true
    skip_join: true
  slack:
    secure: "yY05S8ecxMv5GwexGQV/9sqUwxn1j0LF8KyG0VnoMPqJXOaGmkAe60I695CC7/P0AaNC2oWfqMZcEcdXZNa8l7kWluxyRktt6cP+VDPmIKJqcsasoDPDTLlZQTNy8i+EwxzRWDUUMFjLet6lqZYEbBPeCSufmQyyjknhGiSPGsQ="
  webhooks:
    urls:
      secure: "x6M1u9SFv2oQpo28wDSpURV0Rnk+jTA5VCXIjlo0ccbEV1IOp36KSJT3A2lSbf2BDlwGlKcbgtMP9dk83So2dhvPow7ogemouW+Rx1olYJgzoTR3v5cZt9pn7g6y0O1M+AkDIzabzT90oRD4//YVY5OS16ZjePcBWwp9yHEEQ7I="

language: perl
perl:
  - "5.14" # wheezy, precise
  - "5.18" # trusty
  - "5.20" # jessie
  - "5.22" # xenial
  - "5.24" # stretch, zesty
# Params::Classify breaks in 5.26, and Lingua::EN::Tagger needs upgrading
#  - "5.26"

cache:
  directories:
    - ~/.npm
    - node_modules

matrix:
  include:
  - perl: "5.22"
    env: "CYPRESS=1"

env:
  global:
    - "S3_BUCKET=fixmystreet-bundle-cache"
    - "CYPRESS=0"
    - secure: "llgWNfR/8pH0HjYpg+xhVxuqTaLC0GGUugfuINiUap7JxzjCZ2rlryxCXA4BCM8GUHa9wlYKhrKCSx+DM3EHRE0cLei7LNxAK1JSXLj3NihFQhqnq64tjDwGCSA4l7mlqErA7DK4Dpmh+hBp5f680akITAInM92CbwQZxLDYaCU="
    - secure: "qW+WCgAF68itADxcbcq+nCnKx3vf3GX73HMfjfbkFFUsYmIR+ZaJ9yQMnGJwxIpCHTWLAeqyx4KO8N8T3GmNdKYzIMZemOzp4ED29YC31QOQeq1CwNp2hD5sq/o47d2BzXWwMYNvNXfxz1K6r2c6EMPUtu8X3B8ExZq1RzSFdXs="

sudo: false

addons:
    apt:
        packages:
            - gettext
            - language-pack-de
            - language-pack-nb

install:
  - .travis/install
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then cpanm --quiet --notest Devel::Cover::Report::Codecov; fi'
  - 'if [ "$CYPRESS" = "1" ]; then npm install cypress; fi'
before_script:
  - commonlib/bin/gettext-makemo FixMyStreet
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then export HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local/lib/perl5,commonlib,perllib/Catalyst/[^A],perllib/DBIx,perllib/Email,perllib/Template,^t"; fi'
script:
  - 'if [ "$CYPRESS" = "0" ]; then script/test --jobs 3 t; fi'
  - 'if [ "$CYPRESS" = "1" ]; then PATH=$(npm bin):$PATH bin/browser-tests run ${CYPRESS_RECORD_KEY:+--record}; fi'
after_success:
  - .travis/after_script
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then cover --report codecov; fi'
